name: Run Cadence tests
on: push

jobs:
  get-recipe-repos:
    runs-on: macos-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dynamically retrieve matrix
        id: set-matrix      
        run: echo "::set-output name=matrix::$(ls src/data/recipes/* | jq -R -s -c 'split("\n")[:-3]')"
  run-cadence-tests:
    needs: get-recipe-repos
    runs-on: macos-latest
    strategy:
        matrix:
            recipe: ${{ fromJson(needs.get-recipe-repos.outputs.matrix) }}
    steps:
       - name: Check out repository code
         uses: actions/checkout@v4
       - name: Install Flow CLI
         run: |
           brew update
           brew install flow-cli
       - name: Trigger recipe test
         run: flow test src/data/recipes/${{ matrix.recipe }}/cadence/tests.cdc
